### ISSUE TITLE
PhoneGap script deployment 

### ISSUE THREAD

**Issue by stbland** [dennisjzh/GwtMobile-PhoneGap#1]
In order to deploy PhoneGap script, you must change  <script src="phonegap-0.9.X.js"/> for <script src="public/phonegap-0.9.X.js"/> .

Tested with GWT 2.2.0

**Comment by dennisjzh** [comment]
@stbland 

Did you close this issue by accident? If you did (that happened before to others), I can re-open the issue for you.

This may not related to your issue, but I have been thinking about moving the phonegap.js file out on the "public" folder and into the "war" folder. The main reason is that the phonegap.js file platform specific, and the one included in GWT Mobile is the Android version. It just seems weird to package a platform specific file in a supposedly cross-platform project. I may just have the index.html load the phonegap.js file from the war folder.

**Comment by stbland** [comment]
Hello,

I wasn't a mistake, in fact I want delete this issue but it's not possible
for me.

Best regards,
Stphane.

PS : sorry for my poor english, I'm french.

2011/4/18 dennisjzh <
reply@reply.github.com>
